name: Build docker image
run-name: Build application
on: [push]

jobs:
  Release-image:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}

      - name: "Build Image"
        run: |
          docker build -t ghcr.io/${{github.actor}}/${GITHUB_REF##*/}:latest -f ${GITHUB_REF##*/}/Dockerfile .
          docker push ghcr.io/${{github.actor}}/${GITHUB_REF##*/}:latest
